module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    ...(process.env.NODE_ENV === 'production' ? {
      cssnano: {
        preset: ['default', {
          discardComments: {
            removeAll: true,
          },
          normalizeWhitespace: true,
          minifySelectors: true,
          minifyParams: true,
          minifyFontValues: true,
          minifyGradients: true,
          minifyTimingFunctions: true,
          minifyLonghand: true,
          minifyColor: true,
          minifyCalc: true,
          minifyZeros: true,
          minifyTransforms: true,
          minifyConvertValues: true,
          minifyBorderRadius: true,
          minifySelectors: true,
          mergeLonghand: true,
          mergeRules: true,
          normalizeUrl: true,
          normalizeCharset: true,
          normalizeDisplayValues: true,
          normalizePositions: true,
          normalizeRepeatStyle: true,
          normalizeString: true,
          normalizeTimingFunctions: true,
          normalizeUnicode: true,
          normalizeUrl: true,
          orderedValues: true,
          reduceIdents: true,
          reduceInitial: true,
          reduceTransforms: true,
          svgo: true,
          uniqueSelectors: true,
        }],
      },
    } : {}),
  },
} 